version: '3.8'

services:
  # Backend FastAPI
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: mistral-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - mistral-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend Next.js - Mode développement pour éviter les problèmes de build
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: mistral-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    depends_on:
      - backend
    volumes:
      # Monter le code source pour hot-reload
      - ./frontend:/app
      - /app/node_modules
    networks:
      - mistral-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

# Réseau personnalisé pour la communication entre services
networks:
  mistral-network:
    driver: bridge